In [11]:
import xarray as xr
import numpy as np
import scipy
import pandas as pd
import h5py

In [140]:
file = '../dat/oco2_L2StdND_24516a_190209_B10206r_200707115206.h5'
#file = '../dat/oco2_L2StdND_24512a_190209_B10004r_200428131455.h5'
#file = '../dat/oco2_L2StdND_24510a_190209_B10004r_200428132746.h5'
#file = '../dat/oco2_L2StdND_24508a_190209_B10004r_200428042835.h5'
#file = '../dat/oco2_L2StdND_24530a_190210_B10206r_200707115140.h5'
DS = xr.open_dataset(file)
test = h5py.File(file, 'r')

In [141]:
#test.keys()

In [142]:
lon = test['RetrievalGeometry']['retrieval_longitude'][...].flatten()
print(lon.min(), lon.max())

-99.89382 -28.778841


In [143]:
lat = test['RetrievalGeometry']['retrieval_latitude'][...].flatten()
print(lat.min(), lat.max())

-79.05023 58.76927


In [144]:
sounding = test['L1bScSoundingReference']['sounding_id_l1b'][...].flatten()

In [145]:
print(sounding.min(), sounding.max())

2019020918375131 2019020919242108


In [136]:
2019020907430138 in sounding

False

In [105]:
2019020920541937 in sounding

False

In [10]:
DS

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
Attributes:
    identifier_product_doi_authority:  http://dx.doi.org/
    identifier_product_doi:            10.5067/6SBROTA57TFH

In [8]:
DS.variables

Frozen({})

In [48]:
lon_w, lon_e = -64.55, -50.108
lat_s, lat_n = -14.2336, 2.251
lon_range = np.logical_and(DS.longitude >= lon_w, DS.longitude <= lon_e)
lat_range = np.logical_and(DS.latitude >= lat_s, DS.latitude <= lat_n)

select = np.where(np.logical_and(lon_range, lat_range))[0]

In [56]:
index = select[0:5]
print(index)
sounding = DS.sounding_id[index]

[62555 62561 62562 62563 62564]


In [57]:
DS.xco2_quality_flag[index]

<xarray.DataArray 'xco2_quality_flag' (sounding_id: 5)>
array([0., 0., 0., 0., 1.], dtype=float32)
Coordinates:
  * sounding_id  (sounding_id) float64 2.015e+15 2.015e+15 ... 2.015e+15
Attributes:
    units:      none
    long_name:  XCO2_Quality_Flag
    comment:    0=Good, 1=Bad

In [58]:
DS.xco2_qf_bitflag[index]

<xarray.DataArray 'xco2_qf_bitflag' (sounding_id: 5)>
array([0., 0., 0., 0., 3.])
Coordinates:
  * sounding_id  (sounding_id) float64 2.015e+15 2.015e+15 ... 2.015e+15
Attributes:
    units:         none
    long_name:     xco2_quality_flag bitflag
    comment:       xco2_quality_flag bit flag
    qf_variables:  co2_ratio, h2o_ratio, altitude_stddev, max_declocking_wco2...

In [59]:
DS.xco2_qf_simple_bitflag[index]

<xarray.DataArray 'xco2_qf_simple_bitflag' (sounding_id: 5)>
array([0., 0., 0., 0., 4.], dtype=float32)
Coordinates:
  * sounding_id  (sounding_id) float64 2.015e+15 2.015e+15 ... 2.015e+15
Attributes:
    units:      none
    long_name:  xco2_quality_flag simple bitflag
    comment:    Bits: 0=Direct Exclusion; 1=Signal-related; 2=Preprocessor-re...

In [61]:
DS.xco2_qf_simple_bitflag[3]

<xarray.DataArray 'xco2_qf_simple_bitflag' ()>
array(69., dtype=float32)
Coordinates:
    sounding_id  float64 2.015e+15
Attributes:
    units:      none
    long_name:  xco2_quality_flag simple bitflag
    comment:    Bits: 0=Direct Exclusion; 1=Signal-related; 2=Preprocessor-re...